name: Docker Image Build - Push GHCR

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: set release date
      run: |
        echo "TAG=$(date +%s)" >> ${GITHUB_ENV}
    
    - name: Docker login 2
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build the base UBI Docker image
      run: docker build . --file Dockerfile --target base --tag ghcr.io/rhel-ubi8-base:${TAG}
      
    - name: Build the UBI Docker image with lustre
      run: docker build . --file Dockerfile --tag ghcr.io/rhel-ubi8-lustre:${TAG}
      
    - name: Tag the base UBI image as latest
      run: docker tag ghcr.io/rhel-ubi8-base:${TAG} ghcr.io/rhel-ubi8-base:latest
      
    - name: Push the base UBI image
      run: docker push ghcr.io/nearnodeflash/rhel-ubi8-base:${TAG}
      
    - name: Push the latest base UBI image
      run: docker push ghcr.io/nearnodeflash/rhel-ubi8-base:latest
      
    - name: Tag the lustre UBI image as latest
      run: docker tag ghcr.io/nearnodeflash/rhel-ubi8-lustre:${TAG} ghcr.io/nearnodeflash/rhel-ubi8-lustre:latest
      
    - name: Push the lustre UBI image
      run: docker push ghcr.io/nearnodeflash/rhel-ubi8-lustre:${TAG}
      
    - name: Push the latest lustre UBI image
      run: docker push ghcr.io/nearnodeflash/rhel-ubi8-lustre:latest
      
